version: '3'

services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: ./apps/portfolio/Dockerfile
    restart: always
    ports:
      - 5030:5030
    networks:
      - app_network

networks:
  app_network:
    external: true
