packages:
  - apps/*
  - packages/*
  - packages/configs/*
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - core-js-pure
  - esbuild
  - prisma
  - sharp
