module.exports = {
  graphql: require("./graphql"),
  html: require("./html"),
  jest: require("./jest"),
  mdx: require("./mdx"),
  playwright: require("./playwright"),
  prettier: require("./prettier"),
  reactQuery: require("./react-query"),
  reactTestingLibrary: require("./react-testing-library"),
  react: require("./react"),
  regexp: require("./regexp"),
  security: require("./security"),
  sonar: require("./sonar"),
  storybook: require("./storybook"),
  tailwind: require("./tailwind"),
  typescript: require("./typescript"),
};
