module.exports = {
  graphql: require('./graphql'),
  html: require('./html'),
  'import-x': require('./import-x'),
  jest: require('./jest'),
  mdx: require('./mdx'),
  'perfectionist-jsx': require('./perfectionist-jsx'),
  perfectionist: require('./perfectionist'),
  performance: require('./performance'),
  playwright: require('./playwright'),
  prettier: require('./prettier'),
  reactQuery: require('./react-query'),
  'react-testing-library': require('./react-testing-library'),
  react: require('./react'),
  regexp: require('./regexp'),
  security: require('./security'),
  'simple-import-sort': require('./simple-import-sort'),
  sonar: require('./sonar'),
  storybook: require('./storybook'),
  tailwind: require('./tailwind'),
  typescript: require('./typescript'),
}
